services:
  postgres:
    image: postgres:16.0
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: omerSolutions
      POSTGRES_PASSWORD: peru2020
      POSTGRES_DB: test-backendJava
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
