CREATE TABLE proyect
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre       VARCHAR(255),
    descripcion  VARCHAR(255),
    estado       VARCHAR(255),
    fecha_inicio TIMESTAMP WITHOUT TIME ZONE,
    fecha_fin    TIMESTAMP WITHOUT TIME ZONE,
    user_id      BIGINT,
    image        OID,
    CONSTRAINT pk_proyect PRIMARY KEY (id)
);

ALTER TABLE proyect
    ADD CONSTRAINT FK_PROYECT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);