CREATE TABLE task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo      VARCHAR(255),
    nombre      VARCHAR(255),
    categoria   VARCHAR(255),
    proyecto_id BIGINT,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_PROYECTO FOREIGN KEY (proyecto_id) REFERENCES proyect (id);