
name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.0
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: omerSolutions
          POSTGRES_PASSWORD: peru2020
          POSTGRES_DB: test-backendJava
        options: >-
          --health-cmd="pg_isready -U omerSolutions -d test-backendJava"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h 127.0.0.1 -p 5432 -U omerSolutions -d test-backendJava; do
          echo "Waiting for database connection..."
          sleep 5
        done

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Run tests
      run: mvn test
